server:
  servlet:
    context-path: /api
  port: 8181
 
spring:
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      enabled: true
  datasource:
    url: jdbc:h2:./persondb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  
  sql:
    init:
      username: sa
      password:
      platform: h2
